name: "Print OIDC Token run"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  print-token:
    runs-on: ubuntu-latest
    steps:
      - name: Get OIDC Token
        run: |
          RAW=$(curl -sSL \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" \
            | jq -r '.value')
          echo "OIDC Token:"
          echo "$RAW"
